CREATE TABLE Person
(
    id       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio      varchar(60),
    gender   varchar(30),
    weight   integer,
    h        integer,
    age      integer,
    calories integer
);

INSERT INTO Person (fio, gender, h, age, calories)
values ('Pankratova U.A.', 'WOMAN', 160, 21, 0)

SELECT *
FROM Person;


DROP TABLE Person
