CREATE TABLE Person
(
    id       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio      varchar(60),
    gender   varchar(30),
    weight   integer,
    h        integer,
    age      integer,
    calories integer
);

CREATE TABLE Ration
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calories integer,
    BZHU varchar(10),
    weight integer,
    description varchar
);



INSERT INTO Person (fio, gender, h, age, calories)
values ('Pankratova U.A.', 'WOMAN', 160, 21, 0);

SELECT *
FROM Ration;

delete
from Person
where id = 9;

DROP TABLE Person;
DROP TABLE Ration;
